  name: PMD  
  on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
        - main
  jobs:
    pmd:
      name: PMD Linter
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
  
        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '11'
  
        - name: Run PMD
          uses: pmd/pmd-github-action@v2
          with:
            rulesets: 'apex_ruleset.xml'
  