# name: Deploy to staging
# on: 
#     workflow_run:
#         workflows: ["swa build"]
#         types:
#             - completed
# jobs: 
#     deploy:
#         runs-on : ubuntu-latest
#         steps:
#             - name : Download artifact
#               uses : actions/download-artifact@v3
#               with : 
#                 name: swa-build
#                 # path: dist/

#             - name : Deploy to azure storage (staging)
#               uses : Azure/static-web-apps-deploy@v1
#               with :
#                 azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_042A80403 }}
#                 repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#                 action: "upload"
#                 ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
#                 # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#                 app_location: "/" # App source code path
#                 # api_location: "api" # Api source code path - optional
#                 output_location: "dist/angular-basic" # Built app content directory - optional
#                 ###### End of Repository/Build Configurations ######

name: Deploy
on:
  workflow_run:
    workflows: ["swa build"]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get run ID of "Test" workflow
        id: get-run-id
        run: |
          OTHER_REPO="Manqoba-stack/not-like-us"
          WF_NAME="swa build"
          RUN_ID=$(gh run list --repo "$OTHER_REPO" --workflow "$WF_NAME" --json databaseId --jq '.[0].databaseId')
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"

        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download artifact from "swa build" workflow
        uses: actions/download-artifact@v4
        with:
          name: swa-build # Match name used in test.yml upload artifact step
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
           
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name : Deploy to azure storage (staging)
        uses : Azure/static-web-apps-deploy@v1
        with :
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_042A80403 }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
            action: "upload"
            skip_app_build: true
            ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
            # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
            app_location: "/" # App source code path
            # api_location: "api" # Api source code path - optional
            output_location: "dist/" # Built app content directory - optional
            ###### End of Repository/Build Configurations ######
           
      - name: Debug build-output files
        run: find ./build-output -type f
          